"""
Example 17 - Workflows: Custom Executors + Agents  (Level: Workflows)
====================================================================

GOAL
    Build a deterministic, graph-based WORKFLOW that mixes plain Python steps
    with AI agents: normalise input -> research -> write -> publish.

WHAT YOU WILL LEARN
    * Agents vs. Workflows:
        - an Agent decides its own steps (LLM-driven, dynamic).
        - a Workflow follows a graph YOU define (predictable, auditable).
    * Executors = workflow nodes. Two ways to write them:
        - ``@executor`` decorator on an async function (quick & simple).
        - a class deriving from ``Executor`` with ``@handler`` methods.
    * Agents can be used directly as nodes; they receive the previous node's
      output and emit an ``AgentExecutorResponse``.
    * ``WorkflowContext[T_Out, T_WorkflowOut]``:
        - ``ctx.send_message(x)``  -> pass ``x`` to the next node(s)
        - ``ctx.yield_output(y)``  -> emit a final workflow output
        - ``ctx.set_state / get_state`` -> share data across nodes
    * ``WorkflowBuilder(...).add_chain([...]).build()`` and streaming events.

RUN
    python examples/04_workflows/17_custom_executor_workflow.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import asyncio  # noqa: E402
from typing import Never  # noqa: E402

from agent_framework import (  # noqa: E402
    Agent,
    AgentExecutorResponse,
    Executor,
    WorkflowBuilder,
    WorkflowContext,
    executor,
    handler,
)

from common import get_chat_client, print_agent, print_header, print_section  # noqa: E402


# ---------------------------------------------------------------------------
# Node 1: function-style executor (input: str, sends: str)
# ---------------------------------------------------------------------------
@executor(id="normalize")
async def normalize(topic: str, ctx: WorkflowContext[str]) -> None:
    """Clean up the raw user input and remember it in shared workflow state."""
    cleaned = " ".join(topic.split()).strip().rstrip("?.!")
    ctx.set_state("original_topic", cleaned)  # visible to every later node
    # The message we send becomes the input of the next node (the researcher agent).
    await ctx.send_message(f"Topic: {cleaned}")


# ---------------------------------------------------------------------------
# Node 4: class-style executor (input: AgentExecutorResponse, yields: str)
# ---------------------------------------------------------------------------
class Publisher(Executor):
    """Formats the writer agent's draft as the final workflow output."""

    def __init__(self) -> None:
        super().__init__(id="publisher")  # every executor needs a unique id

    @handler
    async def publish(self, draft: AgentExecutorResponse, ctx: WorkflowContext[Never, str]) -> None:
        # WorkflowContext[Never, str]: this node sends nothing onward (Never)
        # but yields a str as the workflow's final output.
        topic = ctx.get_state("original_topic")
        text = draft.agent_response.text
        article = f"# {topic.title()}\n\n{text}\n\n---\n({len(text.split())} words, generated by a workflow)"
        await ctx.yield_output(article)


async def main() -> None:
    print_header(
        "17 - Custom Executor Workflow",
        "normalize (python) -> Researcher (agent) -> Writer (agent) -> Publisher (python)",
    )
    client = get_chat_client()

    # Nodes 2 & 3: agents used directly as workflow nodes.
    researcher = Agent(
        client=client,
        name="Researcher",
        instructions="List the 4 most important facts about the given topic as short bullet points.",
    )
    writer = Agent(
        client=client,
        name="Writer",
        instructions="Using the facts in the conversation, write an engaging 120-word blog paragraph.",
    )
    publisher = Publisher()

    # Build the graph. add_chain wires the nodes one after another.
    workflow = (
        WorkflowBuilder(start_executor=normalize, output_from=[publisher])
        .add_chain([normalize, researcher, writer, publisher])
        .build()
    )

    # Stream events so we can watch the graph execute node by node.
    print_section("Execution trace")
    final_output = None
    async for event in workflow.run("   why is the   ocean salty?  ", stream=True):
        if event.type == "executor_invoked":
            print(f"  -> running node: {event.executor_id}")
        elif event.type == "output":
            final_output = event.data

    print_section("Workflow output")
    print_agent("Publisher", str(final_output))


if __name__ == "__main__":
    asyncio.run(main())
